[2024-04-11T17:18:56.267+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:18:56.419+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:18:56.423+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:18:56.423+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2024-04-11T17:18:56.428+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data> on 2024-04-10 17:00:00+00:00
[2024-04-11T17:18:56.434+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4516) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:18:56.435+0000] {standard_task_runner.py:63} INFO - Started process 4518 to run task
[2024-04-11T17:18:56.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2', 'insert_data', 'scheduled__2024-04-10T17:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpidm4sbr4']
[2024-04-11T17:18:56.436+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask insert_data
[2024-04-11T17:18:56.470+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T17:18:56.520+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-10T17:00:00+00:00'
[2024-04-11T17:18:56.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:18:56.531+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-11T17:18:57.455+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-11T17:18:57.458+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:18:57.469+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=22655381_DAG2, task_id=insert_data, execution_date=20240410T170000, start_date=20240411T171856, end_date=20240411T171857
[2024-04-11T17:18:57.509+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T17:18:57.570+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:18:57.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
