[2024-04-11T17:51:01.143+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:51:01.236+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v3.third_task scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-04-11T17:51:01.257+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v3.third_task scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-04-11T17:51:01.269+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-11T17:51:01.301+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): third_task> on 2024-01-19 00:00:00+00:00
[2024-04-11T17:51:01.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v3', 'third_task', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpomjho6a6']
[2024-04-11T17:51:01.317+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask third_task
[2024-04-11T17:51:01.314+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:51:01.319+0000] {standard_task_runner.py:63} INFO - Started process 426 to run task
[2024-04-11T17:51:01.451+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_v3.third_task scheduled__2024-01-19T00:00:00+00:00 [running]> on host caed5d205145
[2024-04-11T17:51:01.738+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-04-11T17:51:01.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:51:01.770+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-11T17:51:01.772+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "This seems like my task 2 is working fine"']
[2024-04-11T17:51:01.793+0000] {subprocess.py:86} INFO - Output:
[2024-04-11T17:51:01.797+0000] {subprocess.py:93} INFO - This seems like my task 2 is working fine
[2024-04-11T17:51:01.803+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-11T17:51:01.808+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:51:01.949+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=first_dag_v3, task_id=third_task, execution_date=20240119T000000, start_date=20240411T175101, end_date=20240411T175101
[2024-04-11T17:51:01.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T17:51:02.061+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:51:02.064+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
