[2024-04-11T17:29:11.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:29:11.887+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:28:00+00:00 [queued]>
[2024-04-11T17:29:11.893+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:28:00+00:00 [queued]>
[2024-04-11T17:29:11.893+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T17:29:11.900+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data> on 2024-04-11 17:28:00+00:00
[2024-04-11T17:29:11.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5349) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:29:11.907+0000] {standard_task_runner.py:63} INFO - Started process 5351 to run task
[2024-04-11T17:29:11.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2', 'insert_data', 'scheduled__2024-04-11T17:28:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpvkowkbcg']
[2024-04-11T17:29:11.908+0000] {standard_task_runner.py:91} INFO - Job 141: Subtask insert_data
[2024-04-11T17:29:11.951+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:28:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T17:29:12.018+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T17:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T17:28:00+00:00'
[2024-04-11T17:29:12.020+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:29:12.034+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-11T17:29:13.283+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-11T17:29:13.292+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:29:13.321+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=22655381_DAG2, task_id=insert_data, execution_date=20240411T172800, start_date=20240411T172911, end_date=20240411T172913
[2024-04-11T17:29:13.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T17:29:13.420+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:29:13.421+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
