[2024-04-11T17:27:08.828+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:27:09.003+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:26:00+00:00 [queued]>
[2024-04-11T17:27:09.007+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:26:00+00:00 [queued]>
[2024-04-11T17:27:09.008+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T17:27:09.014+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data> on 2024-04-11 17:26:00+00:00
[2024-04-11T17:27:09.026+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5170) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:27:09.028+0000] {standard_task_runner.py:63} INFO - Started process 5172 to run task
[2024-04-11T17:27:09.027+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2', 'insert_data', 'scheduled__2024-04-11T17:26:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpvaom5qci']
[2024-04-11T17:27:09.030+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask insert_data
[2024-04-11T17:27:09.071+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-11T17:26:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T17:27:09.121+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T17:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T17:26:00+00:00'
[2024-04-11T17:27:09.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:27:09.135+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-11T17:27:10.129+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-11T17:27:10.133+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:27:10.149+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=22655381_DAG2, task_id=insert_data, execution_date=20240411T172600, start_date=20240411T172709, end_date=20240411T172710
[2024-04-11T17:27:10.169+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T17:27:10.201+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:27:10.203+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
